"""adicionar dados complementares a clientes

Revision ID: 55bc1c686a02
Revises: b645f9c835de
Create Date: 2026-09-22 20:56:57.876717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bc1c686a02'
down_revision: Union[str, Sequence[str], None] = 'b645f9c835de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('telefone', sa.String(length=20), nullable=False)
        )
        batch_op.add_column(
            sa.Column('email', sa.String(length=150), nullable=False)
        )
        batch_op.add_column(
            sa.Column('endereco', sa.String(length=200), nullable=False)
        )
        batch_op.add_column(
            sa.Column('data_nascimento', sa.Date(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('endereco')
        batch_op.drop_column('email')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
