"""adicionar tabela de clientes

Revision ID: b645f9c835de
Revises: 0002_tempo_preparo
Create Date: 2026-09-22 20:01:55.184219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b645f9c835de'
down_revision: Union[str, Sequence[str], None] = '0002_tempo_preparo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
